language: rust
rust:
  - stable
cache: cargo
script:
  - cargo build --release --all
#deploy:
#  provider: releases
#  api_key:
#    secure: TODO: replace token here
#  file: target/release/hashdir
#  on:
#    repo: 47ng/hashdir
#    tags: true
#  skip_cleanup: true
